### ISSUE TITLE
Book must be proofread

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-workbook#25]
The open organization community has finished a _complete manuscript_ of the _Open Organization Workbook_, and the project is now entering formal proofreading.

We welcome—and encourage!—participation from everyone. As @jhibbets put it [last time we did this](https://opensource.com/open-organization/17/6/working-open-and-gsd): "With more eyes, all typos are shallow."

We'll need to complete the proofing process by **December 6, 2017**.

Want to help? Read the instructions and pointers below.

## Proofreading checklist

We'll need lots of help polishing this work. Proofreaders can assist with any or all of the following tasks:

- Locating typos and related copy/paste errors in the book and suggest corrections

- Indicating passages that are ambiguous or otherwise unclear and suggesting potential re-writes

- Confirming proper use of punctuation throughout the book

- Verifying typographic consistency of various chapter components (titles, subtitles, activity steps, tables, figures, etc.)

- Checking opening chapter "fact boxes" to ensure completion and accuracy

- Flagging chapters without completed discussion questions and suggesting potential questions

- Logging incomplete or missing author bios

## Participation instructions

1. Review the book's working [table of contents](https://github.com/open-organization-ambassadors/open-org-workbook/blob/master/open_org_workbook_toc.md).

2. Locate an article that hasn't been proofed. You'll know it hasn't been proofread if it doesn't have someone's initials or username attached to it.

3. Click the "Edit" icon (it's a pencil) in the upper right corner of the table of contents document.

4. Append your initials or username to the chapter(s) you'd like to help proofread. Alternatively, list your preferences in the comments and @semioticrobotic will assign pieces to you.

5. Download the [most recent copy of the book's galley proofs](https://github.com/open-organization-ambassadors/open-org-workbook/blob/master/open_org_workbook_galleys.pdf).

6. Read your selected chapter closely and note the mistakes you discover or changes you'd suggest.

7. List those mistakes and your proposed changes in a comment on this issue.

8. Receive the community's undying gratitude.

**Comment by amusernc** [comment]
AUTHOR | PG | PARAGRAPH/LINE | SUGGESTED EDIT
Whitehurst | 15 | 2/1 | "Senior people" > "Senior leadership teams"
Whitehurst | 15 | 2/2 | Footnote 5 link doesn't work - if that doesn't explain who our repondents are, we need to include it here
Whitehurst | 16 | 2/6 | insert "on" between "not" and "writing"
Whitehurst | 17 | 1/1 | "...in The Open Organization Workbook, a more prescriptive guide to igniting culture change."
Whitehurst | 17 | 2/3 | "...to achieve small, meaningful wins first, as you build..."

**Comment by semioticrobotic** [comment]
Thanks, @amusernc!

**Comment by jhibbets** [comment]
Unit 1 proofs:
- page 42, 2nd p: the product of sharing _of_ something --> the product of sharing something
- page 42, 4th p: should decision-making be hyphenated?
- page 43, Need Phil's bio
- page 44, Missing number of employees in case study box
- page 50, 2nd p: Thoughts like "_Where_ we not... --> Thoughts like "**Were** we not...
- page 50 4th p: But your actions have to meet you ambition --> should ambition be ambitions?
- page 53, Missing number of employees *and* industry in case study box
- page 60, Need @guyma's bio
- page 61, Need review and discussion question (will open a new issue with help wanted)
- page 62, Missing number of employees *and* industry in case study box
- page 65, 1st s: as the following. Should . be a : before the list set?
- page 66, 1 p after Results header: "most recent community meeting" is dating the book, consider: during a retrospective at a past community meeting
- page 68, Missing materials needed from case study box
- page 80, Step 1 - It's not clear to be in there is a facilitator for this exercise and if so, who it should be 
- page 81, Step 9 - seems to be missing something. Encourage everyone to sit down _to begin a group discussion._
@semioticrobotic

**Comment by amusernc** [comment]
@jhibbets @semioticrobotic re: page 42, yes on the hyphenation

**Comment by semioticrobotic** [comment]
Can @pdurbin please give us a hand completing his chapter's fact box?

**Comment by semioticrobotic** [comment]
Reached out to @DreamingInBinary and @guyma for assistance with completing their chapter fact boxes and bio statements.

**Comment by amusernc** [comment]
@jhibbets @semioticrobotic also yes to your question on page 65

**Comment by pdurbin** [comment]
> Can @pdurbin please give us a hand completing his chapter's fact box?

@semioticrobotic when do you need it by?

**Comment by jhibbets** [comment]
Unit 2 proofs:
- page 89 3rd p, (even if we don't often hear about these difference**s** <-- missing s on difference
- page 92, Case study box, Red Hat is at 11,000 associates [1]
- page 105, I'm not really clear what this you are supposed to do with this exercise as I couldn't find an explanation. I _think_ it's to go through the checklist, but the reader is never told this (that I could find)
- page 106, footnotes 26 and 27 are the same reference, not sure if this duplication is needed
- page 108, first bullet, expand JVM for non-technical readers
- page 116, step 5, the reader / facilitator is never told to move chairs into a circle, therefore moving them back into a circle might be confusing. Fix: "Then ask everyone to help move chairs into a circle and sit down."

@semioticrobotic happy thanksgiving!

[1] "As of August 31, 2017 Red Hat had approximately 11,000 employees worldwide." -- https://investors.redhat.com/ir-resources/investor-faqs

**Comment by jhibbets** [comment]
Unit 3 proofs:
- page 130, Employees and Challenge missing from Case Study box
- page 130, 1st para 1) expand CIO for non-technical readers; 2) abbreviate UAB for later in the chapter: University of Alabama Birmingham (UAB)
- page 136, Curtis' bio might be missing a word: In this role **of** servant leader and enabler of others <-- in this role servant leader...sounds strange to me
- page 139, 2nd full p, missing serial comma: implementation, integration**,** and validation 
- page 139, footnote, missing serial comma: detailed design requirements**,** and concept that
- page 142, last p, missing serial comma: 80% of the results, impact**,** and value
- page 142, footnote, missing serial comma: over contract negotiation**,** and responding to change
- page 145, 2nd p, more adaptable/flexible organization_s_ --> more adaptable/flexible organization; organization does not need to be plural here
- page 148, 1st p under Concepts Review: applied --> apply "they can study and apply"
- page 161, missing Catherine's bio
- page 163, Step 1 - this reads as if the facilitator should created slides with yellow and green signs. It might help to clarify that they are making slides for Steps 5 and 7 and the existing three items for physical cards for participants
- page 166, last p, hyphenate decision-making (2nd to last sentence)
- page 173, is missing the page number, 173, on my printout
- page 175, Step 4, I think nonwork should be non-work

@semioticrobotic  that's if for me until next week.

**Comment by semioticrobotic** [comment]
Early next week would be best, @pdurbin. Thanks for your help (hopefully it is not a hassle for you during a holiday week).

**Comment by semioticrobotic** [comment]
Thanks, @jhibbets. Happy Thanksgiving!

**Comment by HeidiHVL** [comment]
Hi @semioticrobotic 

Mark Krake's case study in Collaboration. 

P193
“initially with Compiere and later with ADempiere and metasfresh.” This is confusing. The company is named metasfresh so how did they build software with it? Does Mark mean “initially as” these companies? 

“When we at metasfresh…” I’d probably just say, “When we” or “When our small company” 

P195
Period needed at the end of “Soft skills (e.g., self-responsibility, quality consciousness, solution orientation and more)”

P196
“We provide a secure environment that allows such developments—and also possibilities for communicating about the outcomes, so all can learn from them. “ I’m not sure everyone knows how to create a secure environment for innovation. Can you give an example or two on how a secure environment is achieved?  Eg. By actively listening to participants even if their ideas are not used, or by brainstorming online/asynchronously so that ideas are anonymous, or whatever? 

“So we incorporate all opportunities to improve the own competences in our daily work. “ There are several typos maybe change to … “We incorporate opportunities to improve our competencies in our daily work.” 

P198 Conclusion
“These basics accompany and guide us to this day, even as we are in a process of constant change and improvement.” I might make this a bit stronger by saying “The basic frameworks of a personnel management process based on leadership and participation, and a defined company culture guide us to this day, even as we are in a process of constant change and improvement.”

**Comment by pdurbin** [comment]
> page 66, 1 p after Results header: "most recent community meeting" is dating the book, consider: during a retrospective at a past community meeting

I see someone adjusted this a bit and it looks fine. I'm looking as of this revision: "Working galley proofs produced: November 27, 2017 at 08:28:52". I sort of wonder where the source for to book is because it doesn't seem to be in this git repo.

> Can @pdurbin please give us a hand completing his chapter's fact box?

By "fact box" I assume you mean where "employees" and "industry" are blank.

Industry is easy. You can call it "higher education" or similar.

Number of employees is a bit tricky... I'm looking at our org chart at https://www.iq.harvard.edu/files/iqss-harvard/files/org_chart_8.1.17.pdf and some people work on Dataverse on the side. Please put down "12" for the number of employees.

I hope that's all you need from me but if there's something else, please let me know.

**Comment by semioticrobotic** [comment]
Thanks, @HeidiHVL! Much appreciated. I will reach out to Mark and see if I can incorporate his responses to some of your questions seeking clarification.

**Comment by semioticrobotic** [comment]
Got it, @pdurbin! Appreciate your assistance with that. The source for the book is the ODT file I use to manage the manuscript; we'll be releasing it in the repo (along with the "binary" copies of the book) upon launch!

**Comment by jhibbets** [comment]
Unit 4 proofs
- page 183, last p, there is a random [3,4] that I'm not sure what it goes with or missing references?
- page 186, 1st s after quote, "told what to do by manages as, if there..." should be "told what to do by manages, as if there..." I think cc: @HeidiHVL
- page 186, 2nd p, Google Drive is two words cc: @HeidiHVL
- page 186, also 2nd p, suggest changing "creation of social media tools" to social media _platforms_ cc: @HeidiHVL 
- page 190, I made a note for us to check that startup is used consistently throughout the book, search for start-up so see if we need to correct any with hyphens
- page 190, last p, 1st s, missing serial comma: projects managers, and software devs
- page 190, last p, expand ERP for non-technical readers
- page 191, last s, "Everything, and everybody" Is the comma needed, or there for effect?
- page 193, bulleted list is missing serial commas (3 instances)
- page 194, last p, Issues is capitalized when it should not be 
- page 198, missing details from case study box, cc @jimmysjolund 
- page 198, reference 56 is missing / blank in the footer
- page 205, @jimmysjolund Do you want to add that you are an open org ambassador to your profile?
- page 206, first b, "pair programming" --> paired programming
- page 206, suggestion, third b: A big time thief--and a significant cause of stress--was interruptions, Jimmy said. _Another was to view this is unplanned work._ How can....
- page 207, case study box needs completion @arob98 
- page 211, 1 full p, missing "as" - going to be successful _as_ the team predicts @arob98 
- page 216, missing Challenge from Case Study box 
- page 217, 3rd full p, decisions making --> decision making
- page 218, 1st p - when you get to "practices, providing an answer" this sentence stops making sense to me. I think the parenthesis hurt. Maybe try "patches or merge requests are commonly accepted, and even expected,  practices, (then I don't know how to fix the rest). It could be good, but I'm not reading it well.
- page 221, missing hyphen? Cloud Formation-based tools, also is Cloud Formation a proper noun?
- page 223, suggestion, get rid of 'So What?' sudhead and replace with "Why does inner source matter?"
- page 225, missing review and discussion questions
- page 226, missing elements in Exercise box @ruhbehka 
- page 233, end of 2nd b in Step 1, "every participant" is repeated
- page 240, last p, extra spacing between: _worked [here] at XPRIZE_ ??
- page 243, missing bullet point for "Is it five key outcomes" ? last line in the list
- page 242, example 2: bring ideas to the service or surface?
- page 242, 1st p, In one such workshop _recently_ (remove recently)
- page 242, Step 1: difficult persons --> difficult _personalities_ ??

One more to go @semioticrobotic

**Comment by semioticrobotic** [comment]
Thanks, @jhibbets! incorporating the last of these right now.

Before you read Unit 5, could I ask you to please pull a fresh copy of the galleys? Due to additions and edits, page numbers have shifted and deprecated the numbers with which you're working here (so your helpful page references are always a few pages off the current galleys).

**Comment by jhibbets** [comment]
I printed a new copy for Unit 5 last night before I left the office :)

**Comment by semioticrobotic** [comment]
Always one step ahead. Thanks.

**Comment by jhibbets** [comment]
Unit 5 proofs:
- page 250, 2nd para, does "community at large" need to be at-large? 4th sentence
- page 252, 2nd p, 3rd l, decision making --> decision-making
- page 255, I feel like the intro falls plat at the end--i.e. it just kind of abruptly ends after great detail. Suggestion for @HeidiHVL 

"As you go through this unit and read the case studies and exercise, think about the communities you're part of both professionally and personally. Think about their level of openness and what changes you might incorporate."

- page 256, 2nd p, 4 l, remove "to" from "didn't want _to_ every ounce"
- page 259, 3rd p, 1st/2nd l, day to day --> day-to-day ?
- page 259, 3rd p, 2nd l, reference to digital transformation for non-tech readers, suggest: https://enterprisersproject.com/what-is-digital-transformation 
- page 263, last p, 3 l, remove create from "provides _create_ creates entry points"
- page 264, last p, 1st l, missing of: "the aspect _of_ community is vital"
- page 265 - missing review and discussion questions @jenkelchner 
- page 267, 3rd p, expand IRC for non-tech readers
- page 268, 2nd l, "in turn" may not be needed (make it wordy)
- page 270, last p, 1st l, groups also _how_ their own, how should be host or have
- page 271, 3rd p, 5 l, ad hoc --> ad-hoc (hyphen)
- page 271, 3rd p, 7 l, "this is been" --> this _has_ been
- page 272, last p, hyphenate decision making
- page 273, last line, expand OCHA
- page 275, 2nd p, 6th l, considering --> consider
- page 275 bullet 1 and 2, then page 276 links 4 and 5 could use links (missed opportunity to promote these efforts)

More to come in a bit after getting the kids to bed. tag @semioticrobotic

**Comment by jhibbets** [comment]
more proofs from Unit 5
- page 278, Industry in Case Study box: Civic Technology
- page 278, last p, expand USDS - United Stated Digital Services (USDS)
- page 280, 3rd l from the bottom, extra space between debate and mdash to because
- page 283, last bullet has a period (not needed)
- page 294, 295, and 297 DevHigh5 program is getting broken up when it shouldn't--I found 3 instances
- page 294, last line, missing serial comma: licenses**,** and logos
- page 302, missing serial comma in last bulleted item: knowledge**,** and self governance
- page 303, 2nd p, 1st s, has 2 periods, needs one: "Atkins said.."
- page 308, Exercise box, missing serial comma in materials line: notepads**,** and paper
- page 308, _Question_ on the exercise, should participants read the appendix before the exercise?
- page 309, _Question_ on phase 1, how many people per team?
- page 310, Step 5, 1st s, Ask participants to image --> imagine
- page 315, Step 3, 2nd s, to begin thinking _about_ their (missing about)
- page 318, last line, "by the ones the get voted up" --> "by the ones _that_ get voted up" (replace the with that)
- page 319, 2nd s under add'l resource, "whether is planning" --> "whether _they are_ planning" (replace is with they are)

@semioticrobotic  done!

**Comment by jhibbets** [comment]
@semioticrobotic 

One more fix I saw
- page 316, last line, All at least 20 minutes for **steps 5 and 6**. (replace this step with steps 5 and 6)

**Comment by semioticrobotic** [comment]
Got 'em. Thanks a million, @jhibbets.

**Comment by amusernc** [comment]
Knuth/Kelchner chapter


PG | PARAGRAPH/LINE | SUGGESTED EDIT
-- | -- | --
20 | 1/1 | Who is the "we" mentioned here? Everyone? Management types? Technical types? Red Hatters? Sam and Jen?
20 | 1/5 | "the organization" > "an organization"
20 | 2/2 | "Definition" should be lower case (including in the Appendix)
20 | 3/2 | Add comma following "collaborative"
21 | 4/1 | "In the following pages, we illustrate some common challenges you may encounter when leading (and facing) change in an organization.This should establish context for the example cases you're about to read."
21 | 4/6 | "self awareness" > "self-awareness"
22 | 3/1 | "not sharing" > "Not sharing"
22 | 4/1 | "posting" > "Posting"
22 | 5/1 | "Rapid fire" > Making rapid-fire"
22 | 6/5 | "planned..." > "planned."
23 | 5/2 | "self reflection" > "self-reflection"
23 | 4/4 | "self awareness" > "self-awareness"
24 | 3/1 | add "upon" after "reflecting"
24 | 3/1 | "fears or pain points" or "fears (pain points)" or something similar - otherwise they are separated later in sort of a strange way
24 | 3/7 | don't italicize "fear" - it's already been mentioned - can easily use that as the only word (without "pain points")
24 | 4/2 | move first quotes from before "all" to before "sordid"
25 | 1/1 | "etc" > "etc."
25 | 2/1 | "The Power of Vulnerability" - should have quotation marks around it to denote a book title
25 | 7/3 | Who do we intend as the "your people" here?
26 | 1/2 | "Remember this is a stretch, and it may have been a while since you exercised the ability to reframe your thinking."
26 | 2/5 | Remove "(in one way or another). Address..." and replace with "that we are correct. Take the time to address each of these..."
26 | 3/6-10 | The meaining of the last two sentences isn't clear. Perhaps Jen's section can start out with describing the difference rather than waiting until a few paragraphs later?
27 | 4/3 | remove comma between "potential" and "positive"
27 | 5/3 | add comma after "intelligent"
28 | 7/4 | close quotation after "right thing to do?"
29 | 2/7 | remove em dash and reword to "...rather than to live..."
29 | first line after bullets | "others" should be possessive
30 | 1/1-2 | remove "to each person"
30 | 1/4 | "you fear" should be "your fear"
30 | 4/4 | "that" should be "who"
31 | 1/1 | "frontline" should be hyphenated
31 | 1/4 | "front line" should be hyphenated
31 | 4/1 | make the colon a period
31 | 4/2 | add "and" before "taking"
31 | 4/4 | make " over many iterations" a complete sentence. start the next sentence with "The implementation..."
31 | 5/5 | remove quotation marks around "worth it."
32 | 1/5 | remove comma after "remember" and add "that"
31 | 3/7 | don't think we need "(as I explained before)"
31 | 3/8 | "and" shouldn't be italicized
32 | 4/2 | "...two forces: the power to both drive change and to sustain it."
32 | 4/7 | "..or even unknowingly letting this talent go."
32 | 5/2 | "pause" and "pounce" should be lower case

**Comment by amusernc** [comment]
two general notes:

1. "e.g.," and "i.e.," < this is the correct way to present these, and they are always within the sentence/object referenced - also, there is often misunderstanding re: when to use which so let me know if I can help
2. we should be consistent with the use of the Oxford/serial comma (i.e., the comma before the last "and" in a list) - looks like most recommendations are to use it (which is correct in these cases), but it would be great if we're consistent across the board

**Comment by jhibbets** [comment]
@amusernc I tried to catch as many missing serial comma's on my pass of the
Workbook.

**Comment by amusernc** [comment]
@jhibbets if you're going through this entire workbook, my hat's off to you, sir!

**Comment by amusernc** [comment]
Percoco chapter

PG | PARAGRAPH/LINE | SUGGESTED EDIT
-- | -- | --
88 | 3/9 | "to add to" instead of "to join"
89 | 2/2 | remove "people" from the 2nd and 3rd items in the list: "...people from different cultures, different parts of the world, from different backgronds..."
89 | 3/4 | remove comma from inside the parentheses
89 | 4/5 | "can help you to discover" rather than "can realize"
90 | 1/3 | "a organization" should be "an organization"
90 | 1/4 | "adapt to the community"
90 | 1/5 | "...is difficult for its members..."
90 | 2/6 | remove closed parenthesis after "live by."
90 | 2/7 | "...an environment in which different people can feel comfortable. That, of course, comes with some trade-offs."
90 | 2/10 | "...adapt to its members' needs..."
90 | 3/4 | remove second "uncomfortable"
91 | 1/1 | "that" should be "who"
91 | 3/2 | add comma after "computing"
91 | 3/3 | add comma after "Red Hat"

**Comment by amusernc** [comment]
All three of my selected chapters are done. If there are more chapters remaining on Monday and you need help, feel free to ping me as I may have time to do another one or two. Good luck - and good work!

**Comment by jenkelchner** [comment]
Reply to suggested edits by @amusernc (thanks for the review btw!!) 

Pg 20 1/1: the "we" is business people in general
Pg 24 3/1 & 3/7:  I'm okay with making an edit of some sort, however, fears and pain points are two different things with different perceptions and triggers. 
Pg 25 7/5: "your people" refers to whomever the leader/reader is leading/managing
Pg 26 2/5: prefer it stays as is
Pg 26 3/6-10: happy to think about this some more
Pg 32 5/2:  Pause and Pounce need to stay capitalized and should have the TM added for our trademark as well.  @semioticrobotic this would also be necessary for MaryJo's adaptability exercise.

**Comment by amusernc** [comment]
Reply to @jenkelchner 

pg 20: could you make that a little bit clearer - right now it's just a generic "we" with no point of reference
pg 24, 3/1 and 3/7: agree with your point re: fears and pain points - maybe differentiate them a little more in the paragraph?
pg 32: cool - if those need to be capitalized here, there are some instances earlier in the section where they should also be capitalized but aren't

Thanks for the quick feedback!

**Comment by semioticrobotic** [comment]
Thanks, @amusernc! Amazing work and great catches. Yes, I may assign you one or two more pieces, if you don't mind. More soon.

And @jenkelchner: Weill need to touch base with you on _pause_ and _pounce_.

**Comment by amusernc** [comment]
@semioticrobotic Happy to do what I can.

**Comment by semioticrobotic** [comment]
Would @amusernc have time to review both introductions from @HeidiHVL some time before December 7?

**Comment by amusernc** [comment]
@semioticrobotic Barring any unforeseen circumstances, I should be able to review both of those. If something comes up I'll let you know ASAP, but otherwise expect them on time!

**Comment by amusernc** [comment]
@semioticrobotic Dec 2 galleys seem to be messed up. - When I scroll: 

- Pages 151-200 are missing, and after 150 it starts over at 101
- Pages 201-250 are fine but then start over again twice and I see nothing after 250

Can you please check to see whether this is indeed the case or I'm having strange scrolling issues? Thanks!

**Comment by semioticrobotic** [comment]
Huh. Very strange, @amusernc. In my copy, all those pages are there and intact! Are you downloading the file or trying to load the entire thing straight from GitHub? I've found that doing the latter can occasionally cause issues.

**Comment by semioticrobotic** [comment]
Reminder to @mburke5678 that tomorrow is the final day to submit suggested copy edits.

**Comment by amusernc** [comment]
@semioticrobotic That was the problem. I figured since I didn't have that many pages to proof I'd skip the download. My bad! And thanks!

**Comment by semioticrobotic** [comment]
No worries, @amusernc! May all your problems be as easily solved. Thanks so much for your great work.

**Comment by mburke5678** [comment]
*Introduction: Transparency*
Pg 42 s/transparency is the product of sharing of something/transparency is the product of sharing something 

*How working transparently united our engineers*
Pg 44: In case study box, _Employees_ field empty.
Pg. 47. _From talking around the company, it was clear..._ sounds awkward. Could remove the opening clause and start with _It was clear_ ??
Pg. 50 s/Where not doing/We're not doing ?? Where are we not doing ??
Pg. 51 second paragraph uses _The magic, then_ twice seems redundant. Actually, the first two sentences seem redundant, too. (Maybe I am missing a subtle difference in the two ideas?)

**Comment by semioticrobotic** [comment]
Thanks, @mburke5678! Can you help me understand what your comments market "s/" indicate?

**Comment by amusernc** [comment]
Hess von Ludewig Collaboration chapter


PG | PARAGRAPH/LINE | SUGGESTED EDIT
-- | -- | --
186 | 2/2 | change "cognate" to "associated" or "related"
186 | 2/3 | "Though all these terms refer to some sort of "working together," there are subtle..."
187 | 2/5 | "...traditional businesses, like those with command-and-control hierarchies, manage..."
187 | 4/6 | "we" has not context - perhaps use "the entities" or something similar, as used earlier in the paragraph
188 | 2/7 | "more contentious" should not be italiziced
188 | 2/10 | "discourse" implies more than one-way communication, so I might suggest another word if we want to keep "one-way feedback" in the sentence - this is further emphasized by the first paragraph in "Why is collaboraton important" section on page 189
188 | 5/4 | the "He coordinates" sentence seems redundant after the first one - may want to combine the two somehow if you're shooting for a summary type of idea with the second sentence
189 | 1/1 | remove "on GitHub"
189 | 6/3 | add comma after "e.g."
190 | 3/4 | "knowledge sharing" should be hyphenated
190 | 3/5 | add semi-colon after "communities"
190 | 3/6 | add semi-colon after "Google Drive"
190 | 3/7 | add comma after "YouTube"
191 | 3rd bullet | "decision making" should be hyphenated
191 | 1st after bullets/9 | semi-colon should go inside the quotation marks
191 | last/2 | I would remind readers of the other four values here rather than at the end of the paragraph
192 | 2/7 | "...the focus is on members performing their activities while working out their differences..."
192 | 2/8 | need to clean up the rest of this ^^^ sentence - it's very awkward
192 | 2/12 | "make" > "makes"
192 | 3/1 | change "remind us of" to "reinforces" or something similar
193 | 1/8 | remove the last "s" from "Likins's"
193 | 2/4 | change comma after "together" to a semi-colon and make "It's" lower case
193 | 2/4 | Colon at end of line should be a period
193 | 2/6 | add comma after close of parentheses

**Comment by amusernc** [comment]
@semioticrobotic I won't have time to do the other chapter by tomorrow. If Thursday will work, I can manage it, but I know you have deadlines. I hope someone else has the bandwidth to take it on.

**Comment by semioticrobotic** [comment]
No problem at all, @amusernc. I really appreciate your work on this. Thank you so much!

Update: Through the magic of Find/Replace, I also scanned the entire book and ensured all instance of "i.e." and "e.g." were properly punctuated with commas.

**Comment by HeidiHVL** [comment]
@amusernc thanks for your help with the intro
@semioticrobotic have you made the updates or would you like me to?

**Comment by semioticrobotic** [comment]
I took care of 'em, @HeidiHVL. Thanks!

**Comment by semioticrobotic** [comment]
Thanks for your help, everyone!
