### ISSUE TITLE
Preface needs to be written

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/open-org-workbook#29]
Looks like a bunch of Latin to me. ;)

**Comment by semioticrobotic** [comment]
Thanks! Working on it over the holiday.

**Comment by semioticrobotic** [comment]
Here's a draft. Feedback most definitely welcome!

# Preface

Working on work requires work. That's the premise of this book.

Let me unpack it.

All the stuff we do every day—the activities we pursue, the practices we rehearse to make what we make and ship what we ship—is diffcult and trying _work_. It requires time, energy, perserverance, and skill. We can't often do it alone, so we band with others to pursue it collectively.

And that adds another layer of work. Call it the work of working. It's the work of making sure we're working how we'd like to work, that we're "working well." It involves all the decisions we make, the conversations we have, the meetings we schedule. It's reflective and persistent and messy. But it's important work that directly affects _how_ we do what we do (and whether or not we're successful at doing it!).

We're not always reflexive about the _way_ we work. That's because the way we work (the _style_, the _manner_) is deeply and densely cultural. It exists in all those invisible and unspoken norms, values, and principles that organize our thoughts and guide our behaviors, largely out of view and out of mind.

Recently, though, the _way_ we work—the "organizational culture," as some call it—has become a rather pertinent subject, because more and more people are realizing that it's actually the source of competetive advantage, no matter one's industry or vocation. _How_ people work together, in other words, isn't entirely or easily divorced from _what_ we're working _on_; it's as much a part of _what_ we do as the widgets we ship or the bytes we push.

That's why the open organization community at Opensource.com exists: to sustain and extend a conversation about the way we work at work. Naturally, the community has a specific idea about the best way to work: the _open way_, a manner of working that emphasizes values and principles like transparency, inclusivity, adaptability, collaboration, and community. The community feels adamantly that the _open_ way of working is the _best_ way of working.

For the past two years, the open organization community has been facilitating conversations and collecting stories about an open style of organizing to accomplish work. These stories stress an impressive power to achieve new innovations, respond to new and unforeseen conditions, and deliver value more quickly than we have in the past. That community is also committed to teaching others about this way of working—this _open_ manner of working on work—and helping it flourish around the globe.

We _can_ change our approach to the work of working. But doing so isn't easy. It doesn't happen quickly. It requires sustained attention and focus, systematic and copious care. Working on work requires work.

Hence this book: our community's _work_ book, a resource your team, department, or organization can use to deliberately and effectively alter the way it works. We've designed it to assist you with the difficult work of working on the way you work.

Of course, building it was lots of work. The work of making the workbook for working on work was a community effort. We developed it transparently and collaboratively, in public on GitHub, where it now resides as a living document ready for your modifications and enhancements. Whenever possible, we developed it according to the principles outlined in the Open Decision Framework (see the introduction from Sam Knuth and Jen Kelchner for more). And we organized it according to the tenets of The Open Organization Definition, which is itself a product of the outstanding community of Open Organization Ambassadors who continue to propel this important conversation (see Appendix).

Roll up your sleeves and dig into it. Let's get to work.

**Comment by yevster** [comment]
“We're not always reflexive about the way we work.” -  Do you mean “reflective”?

**Comment by semioticrobotic** [comment]
I was indeed going for "reflexive," @yevster, to indicate a sense of [self-referentiality](https://www.merriam-webster.com/dictionary/reflexive)—but even as I re-read I'm just not sure it really works there. Thanks for pointing it out.

I plan to finalize all feedback, make final edits, and typeset tomorrow.

**Comment by jhibbets** [comment]
Good work BB.

**Comment by semioticrobotic** [comment]
Now typeset!
