### ISSUE TITLE
Mentorship in the Open Organization

### ISSUE THREAD

**Issue by michaelcostello** [open-organization-ambassadors/open-org-workbook#5]
A brief discussion of mentorship in an open organization framework

**Comment by semioticrobotic** [comment]
Thanks, @michaelcostello. Could you provide a bit of extra detail? For example:

- What organization will be the focus of this case study?
- What is the specific nature of the mentor program (i.e., for new hires? for experienced veterans?)
- What is the goal of the mentor program, and what organizational problem/issue is it designed to address?
- In which section of the book do you see this case study appearing?

**Comment by michaelcostello** [comment]
- What organization will be the focus of this case study?

Really any organization that might engage in a mentorship program.
Selfishly, I'd really love it if the focus could be on an engineering org,
a product dev org, or perhaps even a services org :)


   - What is the specific nature of the mentor program (i.e., for new
   hires? for experienced veterans?)

The nature of a mentorship program would be to guide org members through
the org and hope to enable them through that process. This could be new
hires, org members who have been there for a while, all the way up to the
executive level in an org.


   - What is the goal of the mentor program, and what organizational
   problem/issue is it designed to address?

The goal of the mentor program is to assist org members with their
lifecycle in the org. This could be with a view towards how the org member
could be more efficient or "better" at their job, how they might go about
promotion, how to deal with org issues that are unclear or opaque in
nature, or even how to configure a work-life balance while still attending
to org needs. The problem/issue it is intended to address is but not
limited to: employee retention, and employee enablement.


   - In which section of the book do you see this case study appearing?

My hope, which is why I filed the issue against this workbook, is that it
would appear in a functional, "boots on the ground" view, open org
workbook.

Please let me know if any further clarification would help.

Thanks,

Mike

**Comment by semioticrobotic** [comment]
This is very helpful, @michaelcostello. Thanks for offering this detailed explanation.

A chapter on mentoring would be extremely valuable for the workbook. As you [can see](https://github.com/open-organization-ambassadors/open-org-workbook/blob/master/open_org_workbook_toc.md), this book will have two different "types" of materials: case studies and exercises.

**Case studies** are stories about organizations that have experimented with new plans/processes built on open principles. The case studies cover exactly the kinds of questions I put to you above (who did it? why? with what intent? what happened? what can we learn or emulate?). So in this instance, a case study about mentoring would chronicle a mentoring program that arose in response to some organizational need and in line with an open value (e.g., the organization or team realizes that employee retention and engagement are issues, and determines that a mentoring program is necessary, so it builds one in the spirit of making associates more _adaptable_, or maybe enhancing _community_ in the org).

**Exercises** are step-by-step breakdowns of activities or programs that organizations who _want to_ become more open can adopt, enact, or emulate in order to better embrace an open principle and begin acting more openly. So in this instance, a chapter on mentoring would outline (for just one example) something like a 10-step plan for building a mentoring program that enhances community, or maybe the five phases of mentor/mentee development that must occur for a program to be successful.

Hopefully that makes sense. I _believe_ you're looking at something more like an exercise, but I do not want to presume.

**Comment by michaelcostello** [comment]
Bryan, 

I think you make a good point. This would likely fall into more of the "Exercises" category. 

Thanks, 

Mike

**Comment by semioticrobotic** [comment]
Great! Thanks, @michaelcostello. I am working with @LauraHilliger to develop a template/example for the exercises, which I will be sure you can see as you brainstorm directions for your chapter. We hope this will add some uniformity to the materials in the book. In the meantime, I will add you to [the working table of contents](https://github.com/open-organization-ambassadors/open-org-workbook/blob/master/open_org_workbook_toc.md).

**Comment by semioticrobotic** [comment]
How is this going, @michaelcostello?
